package ai.intelliswarm.curator;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import java.io.IOException;
import java.nio.file.*;
import java.time.LocalDateTime;
import java.util.*;

/**
 * Generates CATALOG.md, writes _assessment.json per skill,
 * and moves non-winners to _archived/.
 */
public class CatalogGenerator {

    private static final ObjectMapper MAPPER = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .enable(SerializationFeature.INDENT_OUTPUT)
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

    /**
     * Write all outputs: _assessment.json per skill, archive losers, generate CATALOG.md.
     *
     * @param rankedGroups groups from SkillGrouper, each sorted best-first
     * @param skillsDir    root skills directory
     * @param topK         how many to keep per group
     */
    public void generate(Map<String, List<SkillAssessment>> rankedGroups,
                         Path skillsDir, Path outputDir, int topK) throws IOException {
        var archivedDir = skillsDir.resolve("_archived");
        Files.createDirectories(archivedDir);

        var published = new ArrayList<SkillAssessment>();
        var archived = new ArrayList<SkillAssessment>();

        for (var entry : rankedGroups.entrySet()) {
            var group = entry.getValue();
            for (int i = 0; i < group.size(); i++) {
                var assessment = group.get(i);
                // Re-rank (1-based) now that list is sorted
                var ranked = new SkillAssessment(
                        assessment.skill(), assessment.executionScore(),
                        assessment.effectivenessScore(), assessment.codeQualityScore(),
                        assessment.testCoverageScore(), assessment.uniquenessScore(),
                        assessment.totalScore(), assessment.grade(),
                        assessment.passesCurationBar(), entry.getKey(),
                        i + 1, assessment.assessmentNotes());

                writeAssessmentJson(ranked);

                if (i < topK && ranked.passesCurationBar()) {
                    published.add(ranked);
                } else {
                    archived.add(ranked);
                    archiveSkill(ranked.skill().directory(), archivedDir);
                }
            }
        }

        writeCatalog(published, archived, rankedGroups, outputDir);
    }

    private void writeAssessmentJson(SkillAssessment assessment) throws IOException {
        var dir = assessment.skill().directory();
        if (!Files.exists(dir)) return;

        var json = Map.of(
                "totalScore", assessment.totalScore(),
                "grade", assessment.grade(),
                "dimensions", Map.of(
                        "execution", assessment.executionScore(),
                        "effectiveness", assessment.effectivenessScore(),
                        "codeQuality", assessment.codeQualityScore(),
                        "testCoverage", assessment.testCoverageScore(),
                        "uniqueness", assessment.uniquenessScore()
                ),
                "assessedAt", LocalDateTime.now().toString(),
                "assessmentNotes", assessment.assessmentNotes(),
                "rankInGroup", assessment.rankInGroup(),
                "groupName", assessment.groupName(),
                "passesCurationBar", assessment.passesCurationBar()
        );

        MAPPER.writeValue(dir.resolve("_assessment.json").toFile(), json);
    }

    private void archiveSkill(Path skillDir, Path archivedDir) throws IOException {
        if (!Files.exists(skillDir)) return;
        var target = archivedDir.resolve(skillDir.getFileName());
        if (Files.exists(target)) {
            // Already archived — skip
            return;
        }
        Files.move(skillDir, target, StandardCopyOption.ATOMIC_MOVE);
    }

    private void writeCatalog(List<SkillAssessment> published,
                              List<SkillAssessment> archived,
                              Map<String, List<SkillAssessment>> rankedGroups,
                              Path outputDir) throws IOException {
        var sb = new StringBuilder();
        sb.append("# Curated Skills Catalog\n\n");
        sb.append("> Auto-generated by SkillCurator on %s\n\n".formatted(LocalDateTime.now().toString()));
        sb.append("**Published:** %d | **Archived:** %d | **Groups:** %d\n\n".formatted(
                published.size(), archived.size(), rankedGroups.size()));

        // Published skills table
        sb.append("## Published Skills\n\n");
        sb.append("| Rank | Skill | Group | Score | Grade | Usage | Success Rate |\n");
        sb.append("|------|-------|-------|-------|-------|-------|-------------|\n");

        int globalRank = 1;
        var allPublished = new ArrayList<>(published);
        allPublished.sort(Comparator.comparingInt(SkillAssessment::totalScore).reversed());
        for (var a : allPublished) {
            sb.append("| %d | [%s](skills/%s/SKILL.md) | %s | %d/100 | %s | %d | %.0f%% |\n".formatted(
                    globalRank++,
                    a.skill().slug(),
                    a.skill().slug(),
                    a.groupName(),
                    a.totalScore(),
                    a.grade(),
                    a.skill().usageCount(),
                    a.skill().successRate() * 100
            ));
        }

        // Group breakdown
        sb.append("\n## Group Breakdown\n\n");
        for (var entry : rankedGroups.entrySet()) {
            sb.append("### %s\n\n".formatted(entry.getKey()));
            for (var a : entry.getValue()) {
                var status = a.passesCurationBar() && a.rankInGroup() <= published.size()
                        ? "PUBLISHED" : "ARCHIVED";
                sb.append("- **#%d** %s — %d/100 (%s) — %s\n".formatted(
                        a.rankInGroup(), a.skill().slug(),
                        a.totalScore(), a.grade(), status));
            }
            sb.append("\n");
        }

        // Archived summary
        sb.append("## Archived Skills\n\n");
        sb.append("Moved to `_archived/`. Reasons: lower score within group or below curation bar (60).\n\n");
        for (var a : archived) {
            sb.append("- %s — %d/100 (%s) — group: %s, rank #%d\n".formatted(
                    a.skill().slug(), a.totalScore(), a.grade(),
                    a.groupName(), a.rankInGroup()));
        }

        Files.writeString(outputDir.resolve("CATALOG.md"), sb.toString());
    }
}
